package xsh.raindrops.project.entity;

public class Records {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.records
     *
     * @mbg.generated
     */
    private Integer records;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.id
     *
     * @return the value of records.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.id
     *
     * @param id the value for records.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.name
     *
     * @return the value of records.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.name
     *
     * @param name the value for records.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.records
     *
     * @return the value of records.records
     *
     * @mbg.generated
     */
    public Integer getRecords() {
        return records;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.records
     *
     * @param records the value for records.records
     *
     * @mbg.generated
     */
    public void setRecords(Integer records) {
        this.records = records;
    }

	@Override
	public String toString() {
		return "Records [id=" + id + ", name=" + name + ", records=" + records + "]";
	}
    
    
}