package xsh.raindrops.project.entity;

public class User {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.name
	 *
	 * @mbg.generated
	 */
	private String name;

	public User() {
		super();
		// TODO Auto-generated constructor stub
	}

	public User(Integer id, String name, String info) {
		super();
		this.id = id;
		this.name = name;
		this.info = info;
	}
	
	public User( String name, String info) {
		super();
		this.name = name;
		this.info = info;
	}

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.info
	 *
	 * @mbg.generated
	 */
	private String info;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.id
	 *
	 * @return the value of user.id
	 *
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.id
	 *
	 * @param id
	 *            the value for user.id
	 *
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.name
	 *
	 * @return the value of user.name
	 *
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.name
	 *
	 * @param name
	 *            the value for user.name
	 *
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.info
	 *
	 * @return the value of user.info
	 *
	 * @mbg.generated
	 */
	public String getInfo() {
		return info;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.info
	 *
	 * @param info
	 *            the value for user.info
	 *
	 * @mbg.generated
	 */
	public void setInfo(String info) {
		this.info = info;
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", name=" + name + ", info=" + info + "]";
	}

}